spring.application.name=sb-ecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
#spring.h2.console.path=/h2-console

project.images.path=images/


spring.app.jwtSecret=h7u8k2PZ0rQm7q4Vn0Jv1M9wB8A5fE2x6S3TtYcC4D1KpLZRaHNe
spring.app.jwtExpirationMs=86400000
spring.app.cookie.name=sbEcomCookie


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
